title: Gustavo Alves 
author: gfsalves
email: gustavo.figueiredo.alves@usp.br
twitter_username: gfsalves
github_username: gfsalves
theme: jekyll-theme-minimal
show_excerpts: true
theme: jekyll-theme-minimal
